<?php

namespace AppBundle\Repository;

use AppBundle\Entity\FluxJobType;
use Doctrine\ORM\EntityRepository;

/**
 * FluxJobTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FluxJobTypeRepository extends EntityRepository
{
    public function findOneOrCreate(array $name)
    {
        $entity = $this->findOneBy($name);

        if (null === $entity)
        {
            $entity = new FluxJobType();
            $entity->setName($name['name']);
            $this->_em->persist($entity);
            $this->_em->flush();
        }

        return $entity;
    }

    public function getNotComplete()
    {
        $entities = $this->createQueryBuilder('fjt')
            ->where('fjt.jobType IS NULL')
            ->getQuery()
            ->getResult();

        return $entities;
    }
}
