<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FormationPeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationPeriodRepository extends EntityRepository
{
}
