<?php

namespace AppBundle\Repository;

use AppBundle\Entity\JobField;
use Doctrine\ORM\EntityRepository;

/**
 * JobFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobFieldRepository extends EntityRepository
{
    public function findOneOrCreate(array $name)
    {
        $entity = $this->findOneBy($name);

        if (null === $entity)
        {
            $entity = new JobField();
            $entity->setName($name['name']);
            $this->_em->persist($entity);
            $this->_em->flush();
        }

        return $entity;
    }
}
