<?php

namespace AppBundle\Repository;

use AppBundle\Entity\JobType;
use Doctrine\ORM\EntityRepository;

/**
 * JobTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobTypeRepository extends EntityRepository
{
    public function findOneOrCreate(array $name)
    {
        $entity = $this->findOneBy($name);

        if (null === $entity)
        {
            $entity = new JobType();
            $entity->setName($name['name']);
            $this->_em->persist($entity);
            $this->_em->flush();
        }

        return $entity;
    }
}
