# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine


    # Service

    get_object_from_flux:
        class: AppBundle\Service\GetObjectFromFlux
        arguments: [ @doctrine.orm.entity_manager, @form.factory ]

    entity_manager:
        class: AppBundle\Service\EntityManager
        arguments: [ @doctrine.orm.entity_manager ]

    form_factory:
        class: AppBundle\Service\FormFactory
        arguments: [ @form.factory ]

    canal_job.import_system:
        class: AppBundle\Import\ImportInterface
        factory_class: AppBundle\Import\ImportFactory
        factory_method: instanciate
        arguments: [ @request, @doctrine.orm.entity_manager, @form.factory, @validator ]
        scope: request

    # Form

    csv.form:
        class: AppBundle\Form\GetFluxCSVType
        tags:
            - { name: form.type, alias: appbundle_get_csv }

    job.form:
        class: AppBundle\Form\JobType
        tags:
            - { name: form.type, alias: appbundle_job }

    formation.form:
        class: AppBundle\Form\FormationType
        tags:
            - { name: form.type, alias: appbundle_formation }