# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine


    # Service

    canal_job.import_system:
        class: AppBundle\Import\ImportInterface
        factory_class: AppBundle\Import\ImportFactory
        factory_method: instanciate
        arguments: [ @request, @doctrine.orm.entity_manager, @form.factory, @validator ]
        scope: request

    # Form

    csv.form:
        class: AppBundle\Form\GetFluxCSVType
        tags:
            - { name: form.type, alias: appbundle_get_csv }

    job.form:
        class: AppBundle\Form\JobType
        tags:
            - { name: form.type, alias: appbundle_job }

    home.search.job.form:
            class: AppBundle\Form\HomeSearchJobType
            tags:
                - { name: form.type, alias: appbundle_home_search_job }

    home.search.formation.form:
            class: AppBundle\Form\HomeSearchFormationType
            tags:
                - { name: form.type, alias: appbundle_home_search_formation }

    formation.form:
        class: AppBundle\Form\FormationType
        tags:
            - { name: form.type, alias: appbundle_formation }

    # Manager

    job.manager:
        class: AppBundle\Manager\JobManager
        arguments: [ @doctrine.orm.entity_manager, @session ]

    formation.manager:
        class: AppBundle\Manager\FormationManager
        arguments: [ @doctrine.orm.entity_manager, @session ]

    flux_formation_field.manager:
        class: AppBundle\Manager\FluxFormationFieldManager
        arguments: [ @doctrine.orm.entity_manager, @session ]

    flux_formation_type.manager:
        class: AppBundle\Manager\FluxFormationTypeManager
        arguments: [ @doctrine.orm.entity_manager, @session ]

    flux_job_field.manager:
        class: AppBundle\Manager\FluxJobFieldManager
        arguments: [ @doctrine.orm.entity_manager, @session ]

    flux_job_type.manager:
        class: AppBundle\Manager\FluxJobTypeManager
        arguments: [ @doctrine.orm.entity_manager, @session ]
